<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="RevitAPI">
      <SpecificVersion>False</SpecificVersion>
	  <HintPath>..\..\..\API\2027\RevitAPI.dll</HintPath>
	  <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\API\2027\RevitAPIUI.dll</HintPath>
	  <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIIFC">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\API\2027\RevitAPIIFC.dll</HintPath>
	  <Private>False</Private>
    </Reference>
    <Reference Include="UIFramework">
      <HintPath>..\..\..\API\2027\UIFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AdWindows">
      <HintPath>..\..\..\API\2027\AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup />
    <!--
    Always Import the appropriate *.OutputPath.targets file BEFORE the
    Revit.CSharp.targets file, otherwise VisualStudio will complain
    about missing OutputPath tags.
    -->
  <Import Project="$(SolutionDir)VSProps\Revit.CSharp.Sdk.targets" />
</Project>
