//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.IFC.Export.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit.IFC.Export.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conical Face Profile Curve.
        /// </summary>
        internal static string ConicalFaceProfileCurve {
            get {
                return ResourceManager.GetString("ConicalFaceProfileCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export Complete.
        /// </summary>
        internal static string IFCExportComplete {
            get {
                return ResourceManager.GetString("IFCExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Area Schemes: {0} of {1} (Area Scheme ID: {2}).
        /// </summary>
        internal static string IFCProcessingAreaSchemes {
            get {
                return ResourceManager.GetString("IFCProcessingAreaSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Beam Systems: {0} of {1} (Beam System ID: {2}).
        /// </summary>
        internal static string IFCProcessingBeamSystems {
            get {
                return ResourceManager.GetString("IFCProcessingBeamSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Export Zones: {0} of {1} (Export Zone ID: {2}).
        /// </summary>
        internal static string IFCProcessingExportZones {
            get {
                return ResourceManager.GetString("IFCProcessingExportZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Fabric Areas: {0} of {1} (Fabric Area ID: {2}).
        /// </summary>
        internal static string IFCProcessingFabricAreas {
            get {
                return ResourceManager.GetString("IFCProcessingFabricAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Non Spatial Elements: {0} of {1} (Element ID: {2}).
        /// </summary>
        internal static string IFCProcessingNonSpatialElements {
            get {
                return ResourceManager.GetString("IFCProcessingNonSpatialElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Railings: {0} of {1} (Railing ID: {2}).
        /// </summary>
        internal static string IFCProcessingRailings {
            get {
                return ResourceManager.GetString("IFCProcessingRailings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Spatial Elements: {0} of {1} (Element ID: {2}).
        /// </summary>
        internal static string IFCProcessingSpatialElements {
            get {
                return ResourceManager.GetString("IFCProcessingSpatialElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export: Processing Trusses: {0} of {1} (Truss ID: {2}).
        /// </summary>
        internal static string IFCProcessingTrusses {
            get {
                return ResourceManager.GetString("IFCProcessingTrusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Type).
        /// </summary>
        internal static string PropertySetTypeSuffix {
            get {
                return ResourceManager.GetString("PropertySetTypeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolved Face Profile Curve.
        /// </summary>
        internal static string RevolvedFaceProfileCurve {
            get {
                return ResourceManager.GetString("RevolvedFaceProfileCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruled Face Profile Curve.
        /// </summary>
        internal static string RuledFaceProfileCurve {
            get {
                return ResourceManager.GetString("RuledFaceProfileCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        internal static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
    }
}
