<Project Sdk="">
  <PropertyGroup>
    <RootNamespace>Revit.IFC.Common</RootNamespace>
    <AssemblyName>BIMOne.Revit.IFC.Common</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <Prefer32Bit>false</Prefer32Bit>
    <DefineConstants>TRACE;DEBUG;IFC_OPENSOURCE</DefineConstants>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\Debugx64\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <Prefer32Bit>false</Prefer32Bit>
    <DefineConstants>TRACE;IFC_OPENSOURCE</DefineConstants>
    <OutputPath>bin\Releasex64\</OutputPath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <Import Project="$(SolutionDir)VSProps\Revit.CSharp.Sdk.props" />
   <ItemGroup>
      <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
   </ItemGroup>
  <Import Project="$(SolutionDir)VSProps\Revit.CSharp.Sdk.targets" />
  <ItemGroup>
    <Compile Remove="Enums\IFC4x1EntityType.cs" />
    <Compile Remove="Enums\IFC4x2EntityType.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BIMOne.Autodesk.Revit2026.RevitAPI" Version="26.0.10.8" />
    <PackageReference Include="BIMOne.Autodesk.Revit2026.RevitAPIIFC" Version="26.0.10.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
</Project>