//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.IFC.Import.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit.IFC.Import.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC: Created {0} elements out of {1}, {2}% done..
        /// </summary>
        internal static string IFCCreatedElementsInProgress {
            get {
                return ResourceManager.GetString("IFCCreatedElementsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Material #{0}.
        /// </summary>
        internal static string IFCDefaultMaterialName {
            get {
                return ResourceManager.GetString("IFCDefaultMaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link IFC File.
        /// </summary>
        internal static string IFCLinkFile {
            get {
                return ResourceManager.GetString("IFCLinkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open IFC Reference File.
        /// </summary>
        internal static string IFCOpenReferenceFile {
            get {
                return ResourceManager.GetString("IFCOpenReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC: Post-processing {0} entities out of {1}, {2}% done..
        /// </summary>
        internal static string IFCPostProcessEntities {
            get {
                return ResourceManager.GetString("IFCPostProcessEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC: Processed {0} entities..
        /// </summary>
        internal static string IFCProcessedEntities {
            get {
                return ResourceManager.GetString("IFCProcessedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC: Reading {0}.
        /// </summary>
        internal static string IFCReadingFile {
            get {
                return ResourceManager.GetString("IFCReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload IFC File.
        /// </summary>
        internal static string IFCReloadFile {
            get {
                return ResourceManager.GetString("IFCReloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string IFCTypeSchedule {
            get {
                return ResourceManager.GetString("IFCTypeSchedule", resourceCulture);
            }
        }
    }
}
