<Project>
    <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
       <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
   <PropertyGroup>
       <TargetFramework Condition=" '$(TargetFramework)' == '' ">net10.0-windows</TargetFramework>
   </PropertyGroup>
</Project>
