//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.IFC.Export.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIM.IFC.Export.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase to export.
        /// </summary>
        public static string ActivePhase {
            get {
                return ResourceManager.GetString("ActivePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Content.
        /// </summary>
        public static string AdditionalContent {
            get {
                return ResourceManager.GetString("AdditionalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Address....
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Address.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate UI.
        /// </summary>
        public static string AltUIVer {
            get {
                return ResourceManager.GetString("AltUIVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle from True North.
        /// </summary>
        public static string AngleTrueNorth {
            get {
                return ResourceManager.GetString("AngleTrueNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign address to building.
        /// </summary>
        public static string AssignAddressToBuilding {
            get {
                return ResourceManager.GetString("AssignAddressToBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign address to site.
        /// </summary>
        public static string AssignAddressToSite {
            get {
                return ResourceManager.GetString("AssignAddressToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments....
        /// </summary>
        public static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s email.
        /// </summary>
        public static string AuthorsEMail {
            get {
                return ResourceManager.GetString("AuthorsEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s name.
        /// </summary>
        public static string AuthorsName {
            get {
                return ResourceManager.GetString("AuthorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building description.
        /// </summary>
        public static string BuildingDescription {
            get {
                return ResourceManager.GetString("BuildingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building name/number.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building type.
        /// </summary>
        public static string BuildingType {
            get {
                return ResourceManager.GetString("BuildingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Settings....
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the documentation (usually URL).
        /// </summary>
        public static string ClassificationAltLocation {
            get {
                return ResourceManager.GetString("ClassificationAltLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional alternate shared parameter name for this classification (default: ClassificationCode).
        /// </summary>
        public static string ClassificationAltName {
            get {
                return ResourceManager.GetString("ClassificationAltName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification field name.
        /// </summary>
        public static string ClassificationFieldName {
            get {
                return ResourceManager.GetString("ClassificationFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Settings.
        /// </summary>
        public static string ClassificationSetting {
            get {
                return ResourceManager.GetString("ClassificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition number of the Classification system.
        /// </summary>
        public static string ClassificationSystemEdition {
            get {
                return ResourceManager.GetString("ClassificationSystemEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Classification System.
        /// </summary>
        public static string ClassificationSystemName {
            get {
                return ResourceManager.GetString("ClassificationSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source or publisher of the Classification System.
        /// </summary>
        public static string ClassificationSystemSource {
            get {
                return ResourceManager.GetString("ClassificationSystemSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new setup based on the selected setup..
        /// </summary>
        public static string CloneSetup {
            get {
                return ResourceManager.GetString("CloneSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company email.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Info.
        /// </summary>
        public static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company phone.
        /// </summary>
        public static string CompanyPhone {
            get {
                return ResourceManager.GetString("CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company type.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Configuration.
        /// </summary>
        public static string ConfigurationFilePrefix {
            get {
                return ResourceManager.GetString("ConfigurationFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new setup..
        /// </summary>
        public static string CreateNewSetup {
            get {
                return ResourceManager.GetString("CreateNewSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current options:.
        /// </summary>
        public static string CurrentOptions {
            get {
                return ResourceManager.GetString("CurrentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export setup:.
        /// </summary>
        public static string CurrentSelectedSetup {
            get {
                return ResourceManager.GetString("CurrentSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default phase to export.
        /// </summary>
        public static string DefaultPhase {
            get {
                return ResourceManager.GetString("DefaultPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old configuration.
        /// </summary>
        public static string DeleteOldConfiguration {
            get {
                return ResourceManager.GetString("DeleteOldConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old IFC export setups.
        /// </summary>
        public static string DeleteOldSetups {
            get {
                return ResourceManager.GetString("DeleteOldSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected setup..
        /// </summary>
        public static string DeleteSelectedSetup {
            get {
                return ResourceManager.GetString("DeleteSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Low.
        /// </summary>
        public static string DetailLevelExtraLow {
            get {
                return ResourceManager.GetString("DetailLevelExtraLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string DetailLevelHigh {
            get {
                return ResourceManager.GetString("DetailLevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string DetailLevelLow {
            get {
                return ResourceManager.GetString("DetailLevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DetailLevelMedium {
            get {
                return ResourceManager.GetString("DetailLevelMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Point.
        /// </summary>
        public static string DistributionPoint {
            get {
                return ResourceManager.GetString("DistributionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Not Saved.
        /// </summary>
        public static string DocNotSaved {
            get {
                return ResourceManager.GetString("DocNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation location.
        /// </summary>
        public static string DocumentationLocation {
            get {
                return ResourceManager.GetString("DocumentationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastings.
        /// </summary>
        public static string Eastings {
            get {
                return ResourceManager.GetString("Eastings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition date.
        /// </summary>
        public static string EditionDate {
            get {
                return ResourceManager.GetString("EditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        public static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPSG Code.
        /// </summary>
        public static string EPSGCode {
            get {
                return ResourceManager.GetString("EPSGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural Reference Exchange.
        /// </summary>
        public static string ER_Architecture {
            get {
                return ResourceManager.GetString("ER_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string ER_ArchitectureShort {
            get {
                return ResourceManager.GetString("ER_ArchitectureShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEP Reference Exchange.
        /// </summary>
        public static string ER_BuildingService {
            get {
                return ResourceManager.GetString("ER_BuildingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildingService.
        /// </summary>
        public static string ER_BuildingServiceShort {
            get {
                return ResourceManager.GetString("ER_BuildingServiceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural Reference Exchange.
        /// </summary>
        public static string ER_Structural {
            get {
                return ResourceManager.GetString("ER_Structural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural.
        /// </summary>
        public static string ER_StructuralShort {
            get {
                return ResourceManager.GetString("ER_StructuralShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Requirement.
        /// </summary>
        public static string ExchangeRequirement {
            get {
                return ResourceManager.GetString("ExchangeRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities to Export ....
        /// </summary>
        public static string ExcludeEntitySelection {
            get {
                return ResourceManager.GetString("ExcludeEntitySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export base quantities.
        /// </summary>
        public static string ExportBaseQuantities {
            get {
                return ResourceManager.GetString("ExportBaseQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export bounding box.
        /// </summary>
        public static string ExportBoundingBox {
            get {
                return ResourceManager.GetString("ExportBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export only elements visible in current view.
        /// </summary>
        public static string ExportElementsVisibleInView {
            get {
                return ResourceManager.GetString("ExportElementsVisibleInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export IFC.
        /// </summary>
        public static string ExportIFC {
            get {
                return ResourceManager.GetString("ExportIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export IFC common property sets.
        /// </summary>
        public static string ExportIFCCommonPropertySets {
            get {
                return ResourceManager.GetString("ExportIFCCommonPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export internal Revit property sets.
        /// </summary>
        public static string ExportInternalRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportInternalRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export linked files as separate IFCs.
        /// </summary>
        public static string ExportLinkedFiles {
            get {
                return ResourceManager.GetString("ExportLinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export material property sets.
        /// </summary>
        public static string ExportMaterialPropertySets {
            get {
                return ResourceManager.GetString("ExportMaterialPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export parts as building elements.
        /// </summary>
        public static string ExportPartsAsBuildingElements {
            get {
                return ResourceManager.GetString("ExportPartsAsBuildingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export 2D plan view elements.
        /// </summary>
        public static string ExportPlanViewElements {
            get {
                return ResourceManager.GetString("ExportPlanViewElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Revit property sets.
        /// </summary>
        public static string ExportRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export rooms, areas and spaces in 3D views.
        /// </summary>
        public static string ExportRoomsInView {
            get {
                return ResourceManager.GetString("ExportRoomsInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export schedules as property sets.
        /// </summary>
        public static string ExportSchedulesAsPropertySets {
            get {
                return ResourceManager.GetString("ExportSchedulesAsPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export schedules as property sets.
        /// </summary>
        public static string ExportSchedulesAsPsets {
            get {
                return ResourceManager.GetString("ExportSchedulesAsPsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected setup ....
        /// </summary>
        public static string ExportSelectedSetup {
            get {
                return ResourceManager.GetString("ExportSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow use of mixed &quot;Solid Model&quot; representation.
        /// </summary>
        public static string ExportSolidModelsWhenPossible {
            get {
                return ResourceManager.GetString("ExportSolidModelsWhenPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export only schedules containing IFC, Pset, or Common in the title.
        /// </summary>
        public static string ExportSpecificSchedules {
            get {
                return ResourceManager.GetString("ExportSpecificSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export parameter mapping table.
        /// </summary>
        public static string ExportUserDefinedParameterMappingTable {
            get {
                return ResourceManager.GetString("ExportUserDefinedParameterMappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export user defined property sets.
        /// </summary>
        public static string ExportUserDefinedPropertySets {
            get {
                return ResourceManager.GetString("ExportUserDefinedPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined property set file name.
        /// </summary>
        public static string ExportUserDefinedPsetsFileName {
            get {
                return ResourceManager.GetString("ExportUserDefinedPsetsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export only elements visible in view.
        /// </summary>
        public static string ExportVisibleElementsInView {
            get {
                return ResourceManager.GetString("ExportVisibleElementsInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File description.
        /// </summary>
        public static string FileDescription {
            get {
                return ResourceManager.GetString("FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Do you want to replace it?.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Header.
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Header Information....
        /// </summary>
        public static string FileHeaderInformation {
            get {
                return ResourceManager.GetString("FileHeaderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File schema.
        /// </summary>
        public static string FileSchema {
            get {
                return ResourceManager.GetString("FileSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File version.
        /// </summary>
        public static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic Datum.
        /// </summary>
        public static string GeodeticDatum {
            get {
                return ResourceManager.GetString("GeodeticDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic Reference.
        /// </summary>
        public static string GeoReference {
            get {
                return ResourceManager.GetString("GeoReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I specify an export setup?.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I assign IFC Entity and Predefined Type?.
        /// </summary>
        public static string HelpAssignIfcEntity {
            get {
                return ResourceManager.GetString("HelpAssignIfcEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do IFC Entity selections affect export?.
        /// </summary>
        public static string HelpSelectEntityForExport {
            get {
                return ResourceManager.GetString("HelpSelectEntityForExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC.
        /// </summary>
        public static string IFC {
            get {
                return ResourceManager.GetString("IFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC2x3 COBie 2.4 Design Deliverable View.
        /// </summary>
        public static string IFC2x3FM {
            get {
                return ResourceManager.GetString("IFC2x3FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC4 for General Use.
        /// </summary>
        public static string IFC4 {
            get {
                return ResourceManager.GetString("IFC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC4 Design Transfer View [Unofficial].
        /// </summary>
        public static string IFC4DTV {
            get {
                return ResourceManager.GetString("IFC4DTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected export setup is not supported by buildingSMART International. Files created using this setup may not be usable by other software..
        /// </summary>
        public static string IFC4DTVWarning {
            get {
                return ResourceManager.GetString("IFC4DTVWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC4 Reference View.
        /// </summary>
        public static string IFC4RV {
            get {
                return ResourceManager.GetString("IFC4RV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Assignments.
        /// </summary>
        public static string IFCAssignments {
            get {
                return ResourceManager.GetString("IFCAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Entity Selection.
        /// </summary>
        public static string IFCEntitySelection {
            get {
                return ResourceManager.GetString("IFCEntitySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC export.
        /// </summary>
        public static string IFCExport {
            get {
                return ResourceManager.GetString("IFCExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Export Warning.
        /// </summary>
        public static string IFCExportGenericWarning {
            get {
                return ResourceManager.GetString("IFCExportGenericWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IFC export process encountered an error for: {0}..
        /// </summary>
        public static string IFCExportProcessError {
            get {
                return ResourceManager.GetString("IFCExportProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IFC export process encountered an error..
        /// </summary>
        public static string IFCExportProcessGenericError {
            get {
                return ResourceManager.GetString("IFCExportProcessGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifc.
        /// </summary>
        public static string IFCExt {
            get {
                return ResourceManager.GetString("IFCExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC-SPF|*.ifc.
        /// </summary>
        public static string IFCFiles {
            get {
                return ResourceManager.GetString("IFCFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Coordination View 2.0.
        /// </summary>
        public static string IFCMVD2x3CV2 {
            get {
                return ResourceManager.GetString("IFCMVD2x3CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 4 Coordination View 2.0.
        /// </summary>
        public static string IFCMVD4CV2 {
            get {
                return ResourceManager.GetString("IFCMVD4CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC2x3 COBie 2.4 Design Deliverable View.
        /// </summary>
        public static string IFCMVDFMExtendedHandOver {
            get {
                return ResourceManager.GetString("IFCMVDFMExtendedHandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Basic FM Handover View.
        /// </summary>
        public static string IFCMVDFMHandOver {
            get {
                return ResourceManager.GetString("IFCMVDFMHandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 GSA Concept Design BIM 2010.
        /// </summary>
        public static string IFCMVDGSA {
            get {
                return ResourceManager.GetString("IFCMVDGSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Schema version.
        /// </summary>
        public static string IFCSchemaVersion {
            get {
                return ResourceManager.GetString("IFCSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized file type option.
        /// </summary>
        public static string IFCUnknown {
            get {
                return ResourceManager.GetString("IFCUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC version.
        /// </summary>
        public static string IFCVersion {
            get {
                return ResourceManager.GetString("IFCVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x2 Coordination View.
        /// </summary>
        public static string IFCVersion2x2 {
            get {
                return ResourceManager.GetString("IFCVersion2x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Coordination View.
        /// </summary>
        public static string IFCVersion2x3 {
            get {
                return ResourceManager.GetString("IFCVersion2x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Version: .
        /// </summary>
        public static string IFCVersionSelected {
            get {
                return ResourceManager.GetString("IFCVersionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized IFC version.
        /// </summary>
        public static string IFCVersionUnrecognized {
            get {
                return ResourceManager.GetString("IFCVersionUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC XML.
        /// </summary>
        public static string IFCXML {
            get {
                return ResourceManager.GetString("IFCXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifcxml.
        /// </summary>
        public static string IFCXMLExt {
            get {
                return ResourceManager.GetString("IFCXMLExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Foundation Classes XML(.ifcxml)|*.ifcxml.
        /// </summary>
        public static string IFCXMLFiles {
            get {
                return ResourceManager.GetString("IFCXMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipped IFC XML.
        /// </summary>
        public static string IFCXMLZIP {
            get {
                return ResourceManager.GetString("IFCXMLZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifczip.
        /// </summary>
        public static string IFCXMLZIPExt {
            get {
                return ResourceManager.GetString("IFCXMLZIPExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipped Industry Foundation Classes XML(.ifczip)|*.ifczip.
        /// </summary>
        public static string IFCXMLZIPFiles {
            get {
                return ResourceManager.GetString("IFCXMLZIPFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipped IFC.
        /// </summary>
        public static string IFCZIP {
            get {
                return ResourceManager.GetString("IFCZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifczip.
        /// </summary>
        public static string IFCZIPExt {
            get {
                return ResourceManager.GetString("IFCZIPExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipped Industry Foundation Classes(.ifczip)|*.ifczip.
        /// </summary>
        public static string IFCZIPFiles {
            get {
                return ResourceManager.GetString("IFCZIPFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include IFCSite elevation in the site local placement origin.
        /// </summary>
        public static string IncludeIfcSiteElevation {
            get {
                return ResourceManager.GetString("IncludeIfcSiteElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include space boundaries.
        /// </summary>
        public static string IncludeSpaceBoundaries {
            get {
                return ResourceManager.GetString("IncludeSpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Steel Elements.
        /// </summary>
        public static string IncludeSteelElements {
            get {
                return ResourceManager.GetString("IncludeSteelElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;In-Session Setup&gt;.
        /// </summary>
        public static string InSessionConfiguration {
            get {
                return ResourceManager.GetString("InSessionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal address.
        /// </summary>
        public static string InternalAddress {
            get {
                return ResourceManager.GetString("InternalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Origin.
        /// </summary>
        public static string InternalCoordinates {
            get {
                return ResourceManager.GetString("InternalCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Origin oriented in True North.
        /// </summary>
        public static string InternalCoordinatesInTN {
            get {
                return ResourceManager.GetString("InternalCoordinatesInTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal location.
        /// </summary>
        public static string InternalLocation {
            get {
                return ResourceManager.GetString("InternalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep tessellated geometry as triangulation.
        /// </summary>
        public static string KeepTessellatedAsTriangulation {
            get {
                return ResourceManager.GetString("KeepTessellatedAsTriangulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Detail.
        /// </summary>
        public static string LevelOfDetail {
            get {
                return ResourceManager.GetString("LevelOfDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a temporary document for exporting the linked instance(s) for ids: {0}.
        /// </summary>
        public static string LinkInstanceExportCantCreateDoc {
            get {
                return ResourceManager.GetString("LinkInstanceExportCantCreateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document for the linked instance(s) could not be found for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportCantFindDoc {
            get {
                return ResourceManager.GetString("LinkInstanceExportCantFindDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} linked instance(s) could not be exported..
        /// </summary>
        public static string LinkInstanceExportErrorMain {
            get {
                return ResourceManager.GetString("LinkInstanceExportErrorMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the linked instance(s) did not exist for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportErrorPath {
            get {
                return ResourceManager.GetString("LinkInstanceExportErrorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked instance(s) were mirrored for ids: {0}.  To export a mirrored linked instance, mirror the linked geometry and link in the new document..
        /// </summary>
        public static string LinkInstanceExportHasReflection {
            get {
                return ResourceManager.GetString("LinkInstanceExportHasReflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked instance(s) were non-conformal for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportNonConformal {
            get {
                return ResourceManager.GetString("LinkInstanceExportNonConformal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked instance(s) were scaled for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportScaled {
            get {
                return ResourceManager.GetString("LinkInstanceExportScaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import setup ....
        /// </summary>
        public static string LoadSetup {
            get {
                return ResourceManager.GetString("LoadSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory fields Name, Source or Publisher, and Edition cannot be empty..
        /// </summary>
        public static string ManditoryFieldsNotEmpty {
            get {
                return ResourceManager.GetString("ManditoryFieldsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify setup ....
        /// </summary>
        public static string ModifySetup {
            get {
                return ResourceManager.GetString("ModifySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Setup.
        /// </summary>
        public static string ModifySetupTitle {
            get {
                return ResourceManager.GetString("ModifySetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple assignments found in the selected objects..
        /// </summary>
        public static string MultipleAssignments {
            get {
                return ResourceManager.GetString("MultipleAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files.
        /// </summary>
        public static string MultipleFiles {
            get {
                return ResourceManager.GetString("MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New export setup.
        /// </summary>
        public static string NewExportSetup {
            get {
                return ResourceManager.GetString("NewExportSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next....
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity does not have predefined type.
        /// </summary>
        public static string NoPredefinedType {
            get {
                return ResourceManager.GetString("NoPredefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northings.
        /// </summary>
        public static string Northings {
            get {
                return ResourceManager.GetString("Northings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements in this model are very far from the origin in this exported file, which may cause display issues in the receiving software. Please consider using the project base point or site survey point as your coodinate basis..
        /// </summary>
        public static string OffsetDistanceTooLarge {
            get {
                return ResourceManager.GetString("OffsetDistanceTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name.
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase to export.
        /// </summary>
        public static string PhaseToExport {
            get {
                return ResourceManager.GetString("PhaseToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P. O. Box.
        /// </summary>
        public static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PredefinedType selection.
        /// </summary>
        public static string PredefinedTypeSelection {
            get {
                return ResourceManager.GetString("PredefinedTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Base Point.
        /// </summary>
        public static string ProjectBasePoint {
            get {
                return ResourceManager.GetString("ProjectBasePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description.
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Coordinate System Reference.
        /// </summary>
        public static string ProjectedCRS {
            get {
                return ResourceManager.GetString("ProjectedCRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProjectedCRSDesc {
            get {
                return ResourceManager.GetString("ProjectedCRSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectedCRSName {
            get {
                return ResourceManager.GetString("ProjectedCRSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Info.
        /// </summary>
        public static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Base Point oriented in True North.
        /// </summary>
        public static string ProjectInTN {
            get {
                return ResourceManager.GetString("ProjectInTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Base.
        /// </summary>
        public static string ProjectOrigin {
            get {
                return ResourceManager.GetString("ProjectOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project phase.
        /// </summary>
        public static string ProjectPhase {
            get {
                return ResourceManager.GetString("ProjectPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Site.
        /// </summary>
        public static string ProjectSite {
            get {
                return ResourceManager.GetString("ProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects to export:.
        /// </summary>
        public static string ProjectToExport {
            get {
                return ResourceManager.GetString("ProjectToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Sets.
        /// </summary>
        public static string PropertySets {
            get {
                return ResourceManager.GetString("PropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC common only.
        /// </summary>
        public static string PropertySetsIFCCommon {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC common, User-defined.
        /// </summary>
        public static string PropertySetsIFCCommonPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommonPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit only.
        /// </summary>
        public static string PropertySetsInternalRevit {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, User-defined.
        /// </summary>
        public static string PropertySetsInternalRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PropertySetsNone {
            get {
                return ResourceManager.GetString("PropertySetsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common.
        /// </summary>
        public static string PropertySetsRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common, User-defined.
        /// </summary>
        public static string PropertySetsRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules only.
        /// </summary>
        public static string PropertySetsSchedules {
            get {
                return ResourceManager.GetString("PropertySetsSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common, Schedules.
        /// </summary>
        public static string PropertySetsSchedulesPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common, Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, Schedules.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevit {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common, Schedules.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common, Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized property sets.
        /// </summary>
        public static string PropertySetsUnrecognized {
            get {
                return ResourceManager.GetString("PropertySetsUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined only.
        /// </summary>
        public static string PropertySetsUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename export setup.
        /// </summary>
        public static string RenameExportSetup {
            get {
                return ResourceManager.GetString("RenameExportSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the selected setup..
        /// </summary>
        public static string RenameSelectedSetup {
            get {
                return ResourceManager.GetString("RenameSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a reserved Windows device name. Choose another name and try again..
        /// </summary>
        public static string ReservedDeviceName {
            get {
                return ResourceManager.GetString("ReservedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset configurations back to the original settings.
        /// </summary>
        public static string ResetConfigToolTip {
            get {
                return ResourceManager.GetString("ResetConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset override values.
        /// </summary>
        public static string ResetOverrideToolTip {
            get {
                return ResourceManager.GetString("ResetOverrideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetToOriginals {
            get {
                return ResourceManager.GetString("ResetToOriginals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the configurations into the document.
        /// </summary>
        public static string SaveChangesTooltip {
            get {
                return ResourceManager.GetString("SaveChangesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to IFC export configuration.
        /// </summary>
        public static string SaveConfigurationChanges {
            get {
                return ResourceManager.GetString("SaveConfigurationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Setup &amp;amp; Close.
        /// </summary>
        public static string SaveSetupAndClose {
            get {
                return ResourceManager.GetString("SaveSetupAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one project to export..
        /// </summary>
        public static string SelectOneOrMoreProjects {
            get {
                return ResourceManager.GetString("SelectOneOrMoreProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Export As IFC Entity.
        /// </summary>
        public static string SelectSingleElement {
            get {
                return ResourceManager.GetString("SelectSingleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Coordinates.
        /// </summary>
        public static string SharedCoordinates {
            get {
                return ResourceManager.GetString("SharedCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked entities.
        /// </summary>
        public static string ShowChecked {
            get {
                return ResourceManager.GetString("ShowChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-checked entities.
        /// </summary>
        public static string ShowUnchecked {
            get {
                return ResourceManager.GetString("ShowUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site description.
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site location.
        /// </summary>
        public static string SiteLocation {
            get {
                return ResourceManager.GetString("SiteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Point.
        /// </summary>
        public static string SiteSurveyPoint {
            get {
                return ResourceManager.GetString("SiteSurveyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file name.
        /// </summary>
        public static string SourceFileName {
            get {
                return ResourceManager.GetString("SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source (Publisher).
        /// </summary>
        public static string SourcePublisher {
            get {
                return ResourceManager.GetString("SourcePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space boundaries.
        /// </summary>
        public static string SpaceBoundaries {
            get {
                return ResourceManager.GetString("SpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Level.
        /// </summary>
        public static string SpaceBoundaries1stLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries1stLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Level.
        /// </summary>
        public static string SpaceBoundaries2ndLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries2ndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SpaceBoundariesNone {
            get {
                return ResourceManager.GetString("SpaceBoundariesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized space boundary level.
        /// </summary>
        public static string SpaceBoundariesUnrecognized {
            get {
                return ResourceManager.GetString("SpaceBoundariesUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Walls, Columns, Ducts by Level.
        /// </summary>
        public static string SplitWallsColumsDuctsByLevel {
            get {
                return ResourceManager.GetString("SplitWallsColumsDuctsByLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the IFC GUID in an element parameter after export.
        /// </summary>
        public static string StoreIFCGUID {
            get {
                return ResourceManager.GetString("StoreIFCGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of detail for some element geometry.
        /// </summary>
        public static string TessellationDetails {
            get {
                return ResourceManager.GetString("TessellationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown alternate UI version.
        /// </summary>
        public static string UnkownAltUIVer {
            get {
                return ResourceManager.GetString("UnkownAltUIVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IFC export setups.
        /// </summary>
        public static string UpdateExportSetups {
            get {
                return ResourceManager.GetString("UpdateExportSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update project address.
        /// </summary>
        public static string UpdateProjectAddress {
            get {
                return ResourceManager.GetString("UpdateProjectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update project information.
        /// </summary>
        public static string UpdateProjectInformation {
            get {
                return ResourceManager.GetString("UpdateProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2D room boundaries for room volume.
        /// </summary>
        public static string Use2DRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("Use2DRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use active view when creating geometry.
        /// </summary>
        public static string UseActiveViewForGeometry {
            get {
                return ResourceManager.GetString("UseActiveViewForGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use coarse tessellation for some BReps.
        /// </summary>
        public static string UseCoarseTessellation {
            get {
                return ResourceManager.GetString("UseCoarseTessellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use coarse tessellation for some BReps and profiles.
        /// </summary>
        public static string UseCoarseTessellationForBReps {
            get {
                return ResourceManager.GetString("UseCoarseTessellationForBReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use family and type name for reference.
        /// </summary>
        public static string UseFamilyAndTypeNameForReference {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use family and type name for references.
        /// </summary>
        public static string UseFamilyAndTypeNameForReferences {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Tessellated Geometry as Triangulation.
        /// </summary>
        public static string UseOnlyTriangulation {
            get {
                return ResourceManager.GetString("UseOnlyTriangulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        public static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom parameter mapping table.
        /// </summary>
        public static string UserDefinedParameterMappingTable {
            get {
                return ResourceManager.GetString("UserDefinedParameterMappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom parameter sets.
        /// </summary>
        public static string UserDefinedParameterSets {
            get {
                return ResourceManager.GetString("UserDefinedParameterSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined purpose.
        /// </summary>
        public static string UserDefinedPurpose {
            get {
                return ResourceManager.GetString("UserDefinedPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2D room boundaries for room volume.
        /// </summary>
        public static string UseRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("UseRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Type name only for IFCType name.
        /// </summary>
        public static string UseTypeNameOnlyForIfcType {
            get {
                return ResourceManager.GetString("UseTypeNameOnlyForIfcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use visible Revit name as the IFCEntity name.
        /// </summary>
        public static string UseVisibleRevitNameAsEntityName {
            get {
                return ResourceManager.GetString("UseVisibleRevitNameAsEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist.
        /// </summary>
        public static string ValidPathExists {
            get {
                return ResourceManager.GetString("ValidPathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...value is set according to export option.
        /// </summary>
        public static string ValueSetByExportOption {
            get {
                return ResourceManager.GetString("ValueSetByExportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...value will be set on export.
        /// </summary>
        public static string ValueSetOnExport {
            get {
                return ResourceManager.GetString("ValueSetOnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v..
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version number.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
    }
}
