//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.IFC.Export.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIM.IFC.Export.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phase to export ähnelt.
        /// </summary>
        public static string ActivePhase {
            get {
                return ResourceManager.GetString("ActivePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional Content ähnelt.
        /// </summary>
        public static string AdditionalContent {
            get {
                return ResourceManager.GetString("AdditionalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Address... ähnelt.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Address ähnelt.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address line 1 ähnelt.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address line 2 ähnelt.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternate UI ähnelt.
        /// </summary>
        public static string AltUIVer {
            get {
                return ResourceManager.GetString("AltUIVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angle from True North ähnelt.
        /// </summary>
        public static string AngleTrueNorth {
            get {
                return ResourceManager.GetString("AngleTrueNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application name ähnelt.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assign address to building ähnelt.
        /// </summary>
        public static string AssignAddressToBuilding {
            get {
                return ResourceManager.GetString("AssignAddressToBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assign address to site ähnelt.
        /// </summary>
        public static string AssignAddressToSite {
            get {
                return ResourceManager.GetString("AssignAddressToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assignments... ähnelt.
        /// </summary>
        public static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorization ähnelt.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author&apos;s email ähnelt.
        /// </summary>
        public static string AuthorsEMail {
            get {
                return ResourceManager.GetString("AuthorsEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author&apos;s name ähnelt.
        /// </summary>
        public static string AuthorsName {
            get {
                return ResourceManager.GetString("AuthorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ... ähnelt.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Building description ähnelt.
        /// </summary>
        public static string BuildingDescription {
            get {
                return ResourceManager.GetString("BuildingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Building name/number ähnelt.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Building type ähnelt.
        /// </summary>
        public static string BuildingType {
            get {
                return ResourceManager.GetString("BuildingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City ähnelt.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classification Settings... ähnelt.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of the documentation (usually URL) ähnelt.
        /// </summary>
        public static string ClassificationAltLocation {
            get {
                return ResourceManager.GetString("ClassificationAltLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The optional alternate shared parameter name for this classification (default: ClassificationCode) ähnelt.
        /// </summary>
        public static string ClassificationAltName {
            get {
                return ResourceManager.GetString("ClassificationAltName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classification field name ähnelt.
        /// </summary>
        public static string ClassificationFieldName {
            get {
                return ResourceManager.GetString("ClassificationFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classification Settings ähnelt.
        /// </summary>
        public static string ClassificationSetting {
            get {
                return ResourceManager.GetString("ClassificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edition number of the Classification system ähnelt.
        /// </summary>
        public static string ClassificationSystemEdition {
            get {
                return ResourceManager.GetString("ClassificationSystemEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the Classification System ähnelt.
        /// </summary>
        public static string ClassificationSystemName {
            get {
                return ResourceManager.GetString("ClassificationSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source or publisher of the Classification System ähnelt.
        /// </summary>
        public static string ClassificationSystemSource {
            get {
                return ResourceManager.GetString("ClassificationSystemSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new setup based on the selected setup. ähnelt.
        /// </summary>
        public static string CloneSetup {
            get {
                return ResourceManager.GetString("CloneSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collapse All ähnelt.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company email ähnelt.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company Info ähnelt.
        /// </summary>
        public static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company name ähnelt.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company phone ähnelt.
        /// </summary>
        public static string CompanyPhone {
            get {
                return ResourceManager.GetString("CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company type ähnelt.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC Configuration ähnelt.
        /// </summary>
        public static string ConfigurationFilePrefix {
            get {
                return ResourceManager.GetString("ConfigurationFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country ähnelt.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new setup. ähnelt.
        /// </summary>
        public static string CreateNewSetup {
            get {
                return ResourceManager.GetString("CreateNewSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current options: ähnelt.
        /// </summary>
        public static string CurrentOptions {
            get {
                return ResourceManager.GetString("CurrentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current selected setup: ähnelt.
        /// </summary>
        public static string CurrentSelectedSetup {
            get {
                return ResourceManager.GetString("CurrentSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ({0}) ähnelt.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default phase to export ähnelt.
        /// </summary>
        public static string DefaultPhase {
            get {
                return ResourceManager.GetString("DefaultPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete old configuration ähnelt.
        /// </summary>
        public static string DeleteOldConfiguration {
            get {
                return ResourceManager.GetString("DeleteOldConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete old IFC export setups ähnelt.
        /// </summary>
        public static string DeleteOldSetups {
            get {
                return ResourceManager.GetString("DeleteOldSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete the selected setup. ähnelt.
        /// </summary>
        public static string DeleteSelectedSetup {
            get {
                return ResourceManager.GetString("DeleteSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extra Low ähnelt.
        /// </summary>
        public static string DetailLevelExtraLow {
            get {
                return ResourceManager.GetString("DetailLevelExtraLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High ähnelt.
        /// </summary>
        public static string DetailLevelHigh {
            get {
                return ResourceManager.GetString("DetailLevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low ähnelt.
        /// </summary>
        public static string DetailLevelLow {
            get {
                return ResourceManager.GetString("DetailLevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string DetailLevelMedium {
            get {
                return ResourceManager.GetString("DetailLevelMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distribution Point ähnelt.
        /// </summary>
        public static string DistributionPoint {
            get {
                return ResourceManager.GetString("DistributionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Not Saved ähnelt.
        /// </summary>
        public static string DocNotSaved {
            get {
                return ResourceManager.GetString("DocNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documentation location ähnelt.
        /// </summary>
        public static string DocumentationLocation {
            get {
                return ResourceManager.GetString("DocumentationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eastings ähnelt.
        /// </summary>
        public static string Eastings {
            get {
                return ResourceManager.GetString("Eastings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edition ähnelt.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edition date ähnelt.
        /// </summary>
        public static string EditionDate {
            get {
                return ResourceManager.GetString("EditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elevation ähnelt.
        /// </summary>
        public static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPSG Code ähnelt.
        /// </summary>
        public static string EPSGCode {
            get {
                return ResourceManager.GetString("EPSGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Architectural Reference Exchange ähnelt.
        /// </summary>
        public static string ER_Architecture {
            get {
                return ResourceManager.GetString("ER_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Architecture ähnelt.
        /// </summary>
        public static string ER_ArchitectureShort {
            get {
                return ResourceManager.GetString("ER_ArchitectureShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MEP Reference Exchange ähnelt.
        /// </summary>
        public static string ER_BuildingService {
            get {
                return ResourceManager.GetString("ER_BuildingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BuildingService ähnelt.
        /// </summary>
        public static string ER_BuildingServiceShort {
            get {
                return ResourceManager.GetString("ER_BuildingServiceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structural Reference Exchange ähnelt.
        /// </summary>
        public static string ER_Structural {
            get {
                return ResourceManager.GetString("ER_Structural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structural ähnelt.
        /// </summary>
        public static string ER_StructuralShort {
            get {
                return ResourceManager.GetString("ER_StructuralShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exchange Requirement ähnelt.
        /// </summary>
        public static string ExchangeRequirement {
            get {
                return ResourceManager.GetString("ExchangeRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entities to Export ... ähnelt.
        /// </summary>
        public static string ExcludeEntitySelection {
            get {
                return ResourceManager.GetString("ExcludeEntitySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expand All ähnelt.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export base quantities ähnelt.
        /// </summary>
        public static string ExportBaseQuantities {
            get {
                return ResourceManager.GetString("ExportBaseQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export bounding box ähnelt.
        /// </summary>
        public static string ExportBoundingBox {
            get {
                return ResourceManager.GetString("ExportBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export only elements visible in current view ähnelt.
        /// </summary>
        public static string ExportElementsVisibleInView {
            get {
                return ResourceManager.GetString("ExportElementsVisibleInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export IFC ähnelt.
        /// </summary>
        public static string ExportIFC {
            get {
                return ResourceManager.GetString("ExportIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export IFC common property sets ähnelt.
        /// </summary>
        public static string ExportIFCCommonPropertySets {
            get {
                return ResourceManager.GetString("ExportIFCCommonPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export internal Revit property sets ähnelt.
        /// </summary>
        public static string ExportInternalRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportInternalRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export linked files as separate IFCs ähnelt.
        /// </summary>
        public static string ExportLinkedFiles {
            get {
                return ResourceManager.GetString("ExportLinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export parts as building elements ähnelt.
        /// </summary>
        public static string ExportPartsAsBuildingElements {
            get {
                return ResourceManager.GetString("ExportPartsAsBuildingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export 2D plan view elements ähnelt.
        /// </summary>
        public static string ExportPlanViewElements {
            get {
                return ResourceManager.GetString("ExportPlanViewElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Revit property sets ähnelt.
        /// </summary>
        public static string ExportRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export rooms, areas and spaces in 3D views ähnelt.
        /// </summary>
        public static string ExportRoomsInView {
            get {
                return ResourceManager.GetString("ExportRoomsInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export schedules as property sets ähnelt.
        /// </summary>
        public static string ExportSchedulesAsPropertySets {
            get {
                return ResourceManager.GetString("ExportSchedulesAsPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export schedules as property sets ähnelt.
        /// </summary>
        public static string ExportSchedulesAsPsets {
            get {
                return ResourceManager.GetString("ExportSchedulesAsPsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save selected setup ... ähnelt.
        /// </summary>
        public static string ExportSelectedSetup {
            get {
                return ResourceManager.GetString("ExportSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow use of mixed &quot;Solid Model&quot; representation ähnelt.
        /// </summary>
        public static string ExportSolidModelsWhenPossible {
            get {
                return ResourceManager.GetString("ExportSolidModelsWhenPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export only schedules containing IFC, Pset, or Common in the title ähnelt.
        /// </summary>
        public static string ExportSpecificSchedules {
            get {
                return ResourceManager.GetString("ExportSpecificSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export parameter mapping table ähnelt.
        /// </summary>
        public static string ExportUserDefinedParameterMappingTable {
            get {
                return ResourceManager.GetString("ExportUserDefinedParameterMappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export user defined property sets ähnelt.
        /// </summary>
        public static string ExportUserDefinedPropertySets {
            get {
                return ResourceManager.GetString("ExportUserDefinedPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User-defined property set file name ähnelt.
        /// </summary>
        public static string ExportUserDefinedPsetsFileName {
            get {
                return ResourceManager.GetString("ExportUserDefinedPsetsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export only elements visible in view ähnelt.
        /// </summary>
        public static string ExportVisibleElementsInView {
            get {
                return ResourceManager.GetString("ExportVisibleElementsInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File description ähnelt.
        /// </summary>
        public static string FileDescription {
            get {
                return ResourceManager.GetString("FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} already exists. Do you want to replace it? ähnelt.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Header ähnelt.
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Header Information... ähnelt.
        /// </summary>
        public static string FileHeaderInformation {
            get {
                return ResourceManager.GetString("FileHeaderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File name: ähnelt.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File schema ähnelt.
        /// </summary>
        public static string FileSchema {
            get {
                return ResourceManager.GetString("FileSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File type ähnelt.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File version ähnelt.
        /// </summary>
        public static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geodetic Datum ähnelt.
        /// </summary>
        public static string GeodeticDatum {
            get {
                return ResourceManager.GetString("GeodeticDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geographic Reference ähnelt.
        /// </summary>
        public static string GeoReference {
            get {
                return ResourceManager.GetString("GeoReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How do I specify an export setup? ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How do I assign IFC Entity and Predefined Type? ähnelt.
        /// </summary>
        public static string HelpAssignIfcEntity {
            get {
                return ResourceManager.GetString("HelpAssignIfcEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How do IFC Entity selections affect export? ähnelt.
        /// </summary>
        public static string HelpSelectEntityForExport {
            get {
                return ResourceManager.GetString("HelpSelectEntityForExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC ähnelt.
        /// </summary>
        public static string IFC {
            get {
                return ResourceManager.GetString("IFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC2x3 COBie 2.4 Design Deliverable View ähnelt.
        /// </summary>
        public static string IFC2x3FM {
            get {
                return ResourceManager.GetString("IFC2x3FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC4 for General Use ähnelt.
        /// </summary>
        public static string IFC4 {
            get {
                return ResourceManager.GetString("IFC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC4 Design Transfer View ähnelt.
        /// </summary>
        public static string IFC4DTV {
            get {
                return ResourceManager.GetString("IFC4DTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC4 Reference View ähnelt.
        /// </summary>
        public static string IFC4RV {
            get {
                return ResourceManager.GetString("IFC4RV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC Assignments ähnelt.
        /// </summary>
        public static string IFCAssignments {
            get {
                return ResourceManager.GetString("IFCAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC Entity Selection ähnelt.
        /// </summary>
        public static string IFCEntitySelection {
            get {
                return ResourceManager.GetString("IFCEntitySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC export ähnelt.
        /// </summary>
        public static string IFCExport {
            get {
                return ResourceManager.GetString("IFCExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The IFC export process encountered an error for: {0}. ähnelt.
        /// </summary>
        public static string IFCExportProcessError {
            get {
                return ResourceManager.GetString("IFCExportProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The IFC export process encountered an error. ähnelt.
        /// </summary>
        public static string IFCExportProcessGenericError {
            get {
                return ResourceManager.GetString("IFCExportProcessGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ifc ähnelt.
        /// </summary>
        public static string IFCExt {
            get {
                return ResourceManager.GetString("IFCExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC-SPF|*.ifc ähnelt.
        /// </summary>
        public static string IFCFiles {
            get {
                return ResourceManager.GetString("IFCFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC 2x3 Coordination View 2.0 ähnelt.
        /// </summary>
        public static string IFCMVD2x3CV2 {
            get {
                return ResourceManager.GetString("IFCMVD2x3CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC 4 Coordination View 2.0 ähnelt.
        /// </summary>
        public static string IFCMVD4CV2 {
            get {
                return ResourceManager.GetString("IFCMVD4CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC2x3 COBie 2.4 Design Deliverable View ähnelt.
        /// </summary>
        public static string IFCMVDFMExtendedHandOver {
            get {
                return ResourceManager.GetString("IFCMVDFMExtendedHandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC 2x3 Basic FM Handover View ähnelt.
        /// </summary>
        public static string IFCMVDFMHandOver {
            get {
                return ResourceManager.GetString("IFCMVDFMHandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC 2x3 GSA Concept Design BIM 2010 ähnelt.
        /// </summary>
        public static string IFCMVDGSA {
            get {
                return ResourceManager.GetString("IFCMVDGSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC Schema version ähnelt.
        /// </summary>
        public static string IFCSchemaVersion {
            get {
                return ResourceManager.GetString("IFCSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized file type option ähnelt.
        /// </summary>
        public static string IFCUnknown {
            get {
                return ResourceManager.GetString("IFCUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC version ähnelt.
        /// </summary>
        public static string IFCVersion {
            get {
                return ResourceManager.GetString("IFCVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC 2x2 Coordination View ähnelt.
        /// </summary>
        public static string IFCVersion2x2 {
            get {
                return ResourceManager.GetString("IFCVersion2x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC 2x3 Coordination View ähnelt.
        /// </summary>
        public static string IFCVersion2x3 {
            get {
                return ResourceManager.GetString("IFCVersion2x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC Version:  ähnelt.
        /// </summary>
        public static string IFCVersionSelected {
            get {
                return ResourceManager.GetString("IFCVersionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized IFC version ähnelt.
        /// </summary>
        public static string IFCVersionUnrecognized {
            get {
                return ResourceManager.GetString("IFCVersionUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC XML ähnelt.
        /// </summary>
        public static string IFCXML {
            get {
                return ResourceManager.GetString("IFCXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ifcxml ähnelt.
        /// </summary>
        public static string IFCXMLExt {
            get {
                return ResourceManager.GetString("IFCXMLExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Industry Foundation Classes XML(.ifcxml)|*.ifcxml ähnelt.
        /// </summary>
        public static string IFCXMLFiles {
            get {
                return ResourceManager.GetString("IFCXMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zipped IFC XML ähnelt.
        /// </summary>
        public static string IFCXMLZIP {
            get {
                return ResourceManager.GetString("IFCXMLZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ifczip ähnelt.
        /// </summary>
        public static string IFCXMLZIPExt {
            get {
                return ResourceManager.GetString("IFCXMLZIPExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zipped Industry Foundation Classes XML(.ifczip)|*.ifczip ähnelt.
        /// </summary>
        public static string IFCXMLZIPFiles {
            get {
                return ResourceManager.GetString("IFCXMLZIPFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zipped IFC ähnelt.
        /// </summary>
        public static string IFCZIP {
            get {
                return ResourceManager.GetString("IFCZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ifczip ähnelt.
        /// </summary>
        public static string IFCZIPExt {
            get {
                return ResourceManager.GetString("IFCZIPExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zipped Industry Foundation Classes(.ifczip)|*.ifczip ähnelt.
        /// </summary>
        public static string IFCZIPFiles {
            get {
                return ResourceManager.GetString("IFCZIPFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include IFCSITE elevation in the site local placement origin ähnelt.
        /// </summary>
        public static string IncludeIfcSiteElevation {
            get {
                return ResourceManager.GetString("IncludeIfcSiteElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include space boundaries ähnelt.
        /// </summary>
        public static string IncludeSpaceBoundaries {
            get {
                return ResourceManager.GetString("IncludeSpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include Steel Elements ähnelt.
        /// </summary>
        public static string IncludeSteelElements {
            get {
                return ResourceManager.GetString("IncludeSteelElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;In-Session Setup&gt; ähnelt.
        /// </summary>
        public static string InSessionConfiguration {
            get {
                return ResourceManager.GetString("InSessionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal address ähnelt.
        /// </summary>
        public static string InternalAddress {
            get {
                return ResourceManager.GetString("InternalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Origin ähnelt.
        /// </summary>
        public static string InternalCoordinates {
            get {
                return ResourceManager.GetString("InternalCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Origin oriented in True North ähnelt.
        /// </summary>
        public static string InternalCoordinatesInTN {
            get {
                return ResourceManager.GetString("InternalCoordinatesInTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal location ähnelt.
        /// </summary>
        public static string InternalLocation {
            get {
                return ResourceManager.GetString("InternalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep tessellated geometry as triangulation ähnelt.
        /// </summary>
        public static string KeepTessellatedAsTriangulation {
            get {
                return ResourceManager.GetString("KeepTessellatedAsTriangulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level of Detail ähnelt.
        /// </summary>
        public static string LevelOfDetail {
            get {
                return ResourceManager.GetString("LevelOfDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not create a temporary document for exporting the linked instance(s) for ids: {0} ähnelt.
        /// </summary>
        public static string LinkInstanceExportCantCreateDoc {
            get {
                return ResourceManager.GetString("LinkInstanceExportCantCreateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document for the linked instance(s) could not be found for ids: {0}. ähnelt.
        /// </summary>
        public static string LinkInstanceExportCantFindDoc {
            get {
                return ResourceManager.GetString("LinkInstanceExportCantFindDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} linked instance(s) could not be exported. ähnelt.
        /// </summary>
        public static string LinkInstanceExportErrorMain {
            get {
                return ResourceManager.GetString("LinkInstanceExportErrorMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The path for the linked instance(s) did not exist for ids: {0}. ähnelt.
        /// </summary>
        public static string LinkInstanceExportErrorPath {
            get {
                return ResourceManager.GetString("LinkInstanceExportErrorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The linked instance(s) were mirrored for ids: {0}.  To export a mirrored linked instance, mirror the linked geometry and link in the new document. ähnelt.
        /// </summary>
        public static string LinkInstanceExportHasReflection {
            get {
                return ResourceManager.GetString("LinkInstanceExportHasReflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The linked instance(s) were non-conformal for ids: {0}. ähnelt.
        /// </summary>
        public static string LinkInstanceExportNonConformal {
            get {
                return ResourceManager.GetString("LinkInstanceExportNonConformal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The linked instance(s) were scaled for ids: {0}. ähnelt.
        /// </summary>
        public static string LinkInstanceExportScaled {
            get {
                return ResourceManager.GetString("LinkInstanceExportScaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import setup ... ähnelt.
        /// </summary>
        public static string LoadSetup {
            get {
                return ResourceManager.GetString("LoadSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mandatory fields Name, Source or Publisher, and Edition cannot be empty. ähnelt.
        /// </summary>
        public static string ManditoryFieldsNotEmpty {
            get {
                return ResourceManager.GetString("ManditoryFieldsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modify setup ... ähnelt.
        /// </summary>
        public static string ModifySetup {
            get {
                return ResourceManager.GetString("ModifySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modify Setup ähnelt.
        /// </summary>
        public static string ModifySetupTitle {
            get {
                return ResourceManager.GetString("ModifySetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple assignments found in the selected objects ! ähnelt.
        /// </summary>
        public static string MultipleAssignments {
            get {
                return ResourceManager.GetString("MultipleAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple files ähnelt.
        /// </summary>
        public static string MultipleFiles {
            get {
                return ResourceManager.GetString("MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New export setup ähnelt.
        /// </summary>
        public static string NewExportSetup {
            get {
                return ResourceManager.GetString("NewExportSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New name ähnelt.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next... ähnelt.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity does not have predefined type ähnelt.
        /// </summary>
        public static string NoPredefinedType {
            get {
                return ResourceManager.GetString("NoPredefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Northings ähnelt.
        /// </summary>
        public static string Northings {
            get {
                return ResourceManager.GetString("Northings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Office ähnelt.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The elements in this model are very far from the origin in this exported file, which may cause display issues in the receiving software. Please consider using the project base point or site survey point as your coodinate basis. ähnelt.
        /// </summary>
        public static string OffsetDistanceTooLarge {
            get {
                return ResourceManager.GetString("OffsetDistanceTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Organization ähnelt.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original name ähnelt.
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Override ähnelt.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phase to export ähnelt.
        /// </summary>
        public static string PhaseToExport {
            get {
                return ResourceManager.GetString("PhaseToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P. O. Box ähnelt.
        /// </summary>
        public static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postal code ähnelt.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PredefinedType selection ähnelt.
        /// </summary>
        public static string PredefinedTypeSelection {
            get {
                return ResourceManager.GetString("PredefinedTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Base Point ähnelt.
        /// </summary>
        public static string ProjectBasePoint {
            get {
                return ResourceManager.GetString("ProjectBasePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project description ähnelt.
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projected Coordinate System Reference ähnelt.
        /// </summary>
        public static string ProjectedCRS {
            get {
                return ResourceManager.GetString("ProjectedCRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string ProjectedCRSDesc {
            get {
                return ResourceManager.GetString("ProjectedCRSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ProjectedCRSName {
            get {
                return ResourceManager.GetString("ProjectedCRSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Info ähnelt.
        /// </summary>
        public static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Base Point oriented in True North ähnelt.
        /// </summary>
        public static string ProjectInTN {
            get {
                return ResourceManager.GetString("ProjectInTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project name ähnelt.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coordinate Base ähnelt.
        /// </summary>
        public static string ProjectOrigin {
            get {
                return ResourceManager.GetString("ProjectOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project phase ähnelt.
        /// </summary>
        public static string ProjectPhase {
            get {
                return ResourceManager.GetString("ProjectPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Site ähnelt.
        /// </summary>
        public static string ProjectSite {
            get {
                return ResourceManager.GetString("ProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects to export: ähnelt.
        /// </summary>
        public static string ProjectToExport {
            get {
                return ResourceManager.GetString("ProjectToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property Sets ähnelt.
        /// </summary>
        public static string PropertySets {
            get {
                return ResourceManager.GetString("PropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC common only ähnelt.
        /// </summary>
        public static string PropertySetsIFCCommon {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC common, User-defined ähnelt.
        /// </summary>
        public static string PropertySetsIFCCommonPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommonPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit only ähnelt.
        /// </summary>
        public static string PropertySetsInternalRevit {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit, User-defined ähnelt.
        /// </summary>
        public static string PropertySetsInternalRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string PropertySetsNone {
            get {
                return ResourceManager.GetString("PropertySetsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit, IFC common ähnelt.
        /// </summary>
        public static string PropertySetsRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit, IFC common, User-defined ähnelt.
        /// </summary>
        public static string PropertySetsRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schedules only ähnelt.
        /// </summary>
        public static string PropertySetsSchedules {
            get {
                return ResourceManager.GetString("PropertySetsSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC Common, Schedules ähnelt.
        /// </summary>
        public static string PropertySetsSchedulesPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC Common, Schedules, User-defined ähnelt.
        /// </summary>
        public static string PropertySetsSchedulesPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit, Schedules ähnelt.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevit {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit, IFC common, Schedules ähnelt.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit, IFC common, Schedules, User-defined ähnelt.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Revit, Schedules, User-defined ähnelt.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schedules, User-defined ähnelt.
        /// </summary>
        public static string PropertySetsSchedulesPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized property sets ähnelt.
        /// </summary>
        public static string PropertySetsUnrecognized {
            get {
                return ResourceManager.GetString("PropertySetsUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User-defined only ähnelt.
        /// </summary>
        public static string PropertySetsUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purpose ähnelt.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename export setup ähnelt.
        /// </summary>
        public static string RenameExportSetup {
            get {
                return ResourceManager.GetString("RenameExportSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename the selected setup. ähnelt.
        /// </summary>
        public static string RenameSelectedSetup {
            get {
                return ResourceManager.GetString("RenameSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is a reserved Windows device name. Choose another name and try again. ähnelt.
        /// </summary>
        public static string ReservedDeviceName {
            get {
                return ResourceManager.GetString("ReservedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset configurations back to the original settings ähnelt.
        /// </summary>
        public static string ResetConfigToolTip {
            get {
                return ResourceManager.GetString("ResetConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset override values ähnelt.
        /// </summary>
        public static string ResetOverrideToolTip {
            get {
                return ResourceManager.GetString("ResetOverrideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string ResetToOriginals {
            get {
                return ResourceManager.GetString("ResetToOriginals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Changes ähnelt.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes to the configurations into the document ähnelt.
        /// </summary>
        public static string SaveChangesTooltip {
            get {
                return ResourceManager.GetString("SaveChangesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes to IFC export configuration ähnelt.
        /// </summary>
        public static string SaveConfigurationChanges {
            get {
                return ResourceManager.GetString("SaveConfigurationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Setup &amp;amp; Close ähnelt.
        /// </summary>
        public static string SaveSetupAndClose {
            get {
                return ResourceManager.GetString("SaveSetupAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select at least one project to export. ähnelt.
        /// </summary>
        public static string SelectOneOrMoreProjects {
            get {
                return ResourceManager.GetString("SelectOneOrMoreProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Export As IFC Entity ähnelt.
        /// </summary>
        public static string SelectSingleElement {
            get {
                return ResourceManager.GetString("SelectSingleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup ähnelt.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared Coordinates ähnelt.
        /// </summary>
        public static string SharedCoordinates {
            get {
                return ResourceManager.GetString("SharedCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checked entities ähnelt.
        /// </summary>
        public static string ShowChecked {
            get {
                return ResourceManager.GetString("ShowChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Un-checked entities ähnelt.
        /// </summary>
        public static string ShowUnchecked {
            get {
                return ResourceManager.GetString("ShowUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site ähnelt.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site description ähnelt.
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site location ähnelt.
        /// </summary>
        public static string SiteLocation {
            get {
                return ResourceManager.GetString("SiteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Survey Point ähnelt.
        /// </summary>
        public static string SiteSurveyPoint {
            get {
                return ResourceManager.GetString("SiteSurveyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source file name ähnelt.
        /// </summary>
        public static string SourceFileName {
            get {
                return ResourceManager.GetString("SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source (Publisher) ähnelt.
        /// </summary>
        public static string SourcePublisher {
            get {
                return ResourceManager.GetString("SourcePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space boundaries ähnelt.
        /// </summary>
        public static string SpaceBoundaries {
            get {
                return ResourceManager.GetString("SpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1st Level ähnelt.
        /// </summary>
        public static string SpaceBoundaries1stLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries1stLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2nd Level ähnelt.
        /// </summary>
        public static string SpaceBoundaries2ndLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries2ndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string SpaceBoundariesNone {
            get {
                return ResourceManager.GetString("SpaceBoundariesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized space boundary level ähnelt.
        /// </summary>
        public static string SpaceBoundariesUnrecognized {
            get {
                return ResourceManager.GetString("SpaceBoundariesUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split Walls, Columns, Ducts by Level ähnelt.
        /// </summary>
        public static string SplitWallsColumsDuctsByLevel {
            get {
                return ResourceManager.GetString("SplitWallsColumsDuctsByLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State/Region ähnelt.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Store the IFC GUID in an element parameter after export ähnelt.
        /// </summary>
        public static string StoreIFCGUID {
            get {
                return ResourceManager.GetString("StoreIFCGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street address ähnelt.
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level of detail for some element geometry ähnelt.
        /// </summary>
        public static string TessellationDetails {
            get {
                return ResourceManager.GetString("TessellationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown alternate UI version ähnelt.
        /// </summary>
        public static string UnkownAltUIVer {
            get {
                return ResourceManager.GetString("UnkownAltUIVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update IFC export setups ähnelt.
        /// </summary>
        public static string UpdateExportSetups {
            get {
                return ResourceManager.GetString("UpdateExportSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update project address ähnelt.
        /// </summary>
        public static string UpdateProjectAddress {
            get {
                return ResourceManager.GetString("UpdateProjectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update project information ähnelt.
        /// </summary>
        public static string UpdateProjectInformation {
            get {
                return ResourceManager.GetString("UpdateProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use 2D room boundaries for room volume ähnelt.
        /// </summary>
        public static string Use2DRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("Use2DRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use active view when creating geometry ähnelt.
        /// </summary>
        public static string UseActiveViewForGeometry {
            get {
                return ResourceManager.GetString("UseActiveViewForGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use coarse tessellation for some BReps ähnelt.
        /// </summary>
        public static string UseCoarseTessellation {
            get {
                return ResourceManager.GetString("UseCoarseTessellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use coarse tessellation for some BReps and profiles ähnelt.
        /// </summary>
        public static string UseCoarseTessellationForBReps {
            get {
                return ResourceManager.GetString("UseCoarseTessellationForBReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use family and type name for reference ähnelt.
        /// </summary>
        public static string UseFamilyAndTypeNameForReference {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use family and type name for references ähnelt.
        /// </summary>
        public static string UseFamilyAndTypeNameForReferences {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep Tessellated Geometry as Triangulation ähnelt.
        /// </summary>
        public static string UseOnlyTriangulation {
            get {
                return ResourceManager.GetString("UseOnlyTriangulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Defined ähnelt.
        /// </summary>
        public static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom parameter mapping table ähnelt.
        /// </summary>
        public static string UserDefinedParameterMappingTable {
            get {
                return ResourceManager.GetString("UserDefinedParameterMappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom parameter sets ähnelt.
        /// </summary>
        public static string UserDefinedParameterSets {
            get {
                return ResourceManager.GetString("UserDefinedParameterSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User-defined purpose ähnelt.
        /// </summary>
        public static string UserDefinedPurpose {
            get {
                return ResourceManager.GetString("UserDefinedPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use 2D room boundaries for room volume ähnelt.
        /// </summary>
        public static string UseRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("UseRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Type name only for IFCType name ähnelt.
        /// </summary>
        public static string UseTypeNameOnlyForIfcType {
            get {
                return ResourceManager.GetString("UseTypeNameOnlyForIfcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use visible Revit name as the IFCEntity name ähnelt.
        /// </summary>
        public static string UseVisibleRevitNameAsEntityName {
            get {
                return ResourceManager.GetString("UseVisibleRevitNameAsEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path does not exist ähnelt.
        /// </summary>
        public static string ValidPathExists {
            get {
                return ResourceManager.GetString("ValidPathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ...value is set according to export option ähnelt.
        /// </summary>
        public static string ValueSetByExportOption {
            get {
                return ResourceManager.GetString("ValueSetByExportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ...value will be set on export ähnelt.
        /// </summary>
        public static string ValueSetOnExport {
            get {
                return ResourceManager.GetString("ValueSetOnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die v. ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version number ähnelt.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
    }
}
