//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Git_Repositories\Revit\Dev2\revit\Source\API\Revit.IFC.Export\Utility\ParamExprGrammar.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Revit.IFC.Export.Utility {

   #pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ParamExprGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IParamExprGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.param_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_expr([NotNull] ParamExprGrammarParser.Param_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.param_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_expr([NotNull] ParamExprGrammarParser.Param_exprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] ParamExprGrammarParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] ParamExprGrammarParser.ExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.atomic_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomic_param([NotNull] ParamExprGrammarParser.Atomic_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.atomic_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomic_param([NotNull] ParamExprGrammarParser.Atomic_paramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.objref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjref([NotNull] ParamExprGrammarParser.ObjrefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.objref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjref([NotNull] ParamExprGrammarParser.ObjrefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] ParamExprGrammarParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] ParamExprGrammarParser.TypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.special_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecial_param([NotNull] ParamExprGrammarParser.Special_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.special_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecial_param([NotNull] ParamExprGrammarParser.Special_paramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.param_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_name([NotNull] ParamExprGrammarParser.Param_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.param_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_name([NotNull] ParamExprGrammarParser.Param_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] ParamExprGrammarParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] ParamExprGrammarParser.NameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_operator([NotNull] ParamExprGrammarParser.Unary_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_operator([NotNull] ParamExprGrammarParser.Unary_operatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.ops"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOps([NotNull] ParamExprGrammarParser.OpsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.ops"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOps([NotNull] ParamExprGrammarParser.OpsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.power_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower_op([NotNull] ParamExprGrammarParser.Power_opContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.power_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower_op([NotNull] ParamExprGrammarParser.Power_opContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ParamExprGrammarParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ParamExprGrammarParser.ValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.value_with_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_with_unit([NotNull] ParamExprGrammarParser.Value_with_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.value_with_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_with_unit([NotNull] ParamExprGrammarParser.Value_with_unitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.stringliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringliteral([NotNull] ParamExprGrammarParser.StringliteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.stringliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringliteral([NotNull] ParamExprGrammarParser.StringliteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.realliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRealliteral([NotNull] ParamExprGrammarParser.RealliteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.realliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRealliteral([NotNull] ParamExprGrammarParser.RealliteralContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamExprGrammarParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigned_number([NotNull] ParamExprGrammarParser.Signed_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamExprGrammarParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigned_number([NotNull] ParamExprGrammarParser.Signed_numberContext context);
}
} // namespace Revit.IFC.Export.Utility
