//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Git_Repositories\Revit\Dev2\revit\Source\API\Revit.IFC.Export\Utility\ParamExprGrammar.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Revit.IFC.Export.Utility {

   #pragma warning disable 3021

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ParamExprGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IParamExprGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.param_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_expr([NotNull] ParamExprGrammarParser.Param_exprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] ParamExprGrammarParser.ExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.atomic_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomic_param([NotNull] ParamExprGrammarParser.Atomic_paramContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.objref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjref([NotNull] ParamExprGrammarParser.ObjrefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] ParamExprGrammarParser.TypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.special_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecial_param([NotNull] ParamExprGrammarParser.Special_paramContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.param_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_name([NotNull] ParamExprGrammarParser.Param_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] ParamExprGrammarParser.NameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] ParamExprGrammarParser.Unary_operatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.ops"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOps([NotNull] ParamExprGrammarParser.OpsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.power_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower_op([NotNull] ParamExprGrammarParser.Power_opContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] ParamExprGrammarParser.ValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.value_with_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_with_unit([NotNull] ParamExprGrammarParser.Value_with_unitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.stringliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringliteral([NotNull] ParamExprGrammarParser.StringliteralContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.realliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealliteral([NotNull] ParamExprGrammarParser.RealliteralContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ParamExprGrammarParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_number([NotNull] ParamExprGrammarParser.Signed_numberContext context);
}
} // namespace Revit.IFC.Export.Utility
